"""Semantic-first vectorization research primitives."""

from curve.anchors import (
    AnchorCandidate,
    AnchorKind,
    CircleAnchor,
    Point,
    QuadAnchor,
    ScoringConfig,
    StrokeAnchor,
    choose_best_anchor,
)
from curve.detection import (
    AnchorThresholdConfig,
    detect_cutout_strokes,
    detect_primitive_anchors,
    primitive_candidates_for_component,
)
from curve.images import ColorMask, flat_color_masks_from_image, scene_from_flat_color_image
from curve.masks import BinaryMask, MaskComponent, connected_components
from curve.scene import (
    SCENE_MANIFEST_SCHEMA_VERSION,
    Scene,
    SvgStyle,
    anchor_to_manifest,
    anchor_to_svg_element,
    anchors_to_debug_svg,
    anchors_to_svg,
    scene_from_mask,
    scene_groups_to_manifest,
    scene_layers_to_manifest,
    scene_metrics_to_manifest,
)
from curve.synthetic import SyntheticSample, generate_synthetic_sample
from curve.runs import (
    VectorizeRun,
    create_run_dir,
    render_html_report,
    render_markdown_report,
    write_html_report,
    write_markdown_report,
    write_vectorize_run,
)
from curve.eval import evaluate_runs, render_eval_markdown, write_eval_summary
from curve.dataset import DatasetSplit, generate_synthetic_dataset, split_counts
from curve.profiling import profile_vectorize
from curve.comparison import (
    compare_git_snapshots,
    compare_snapshots,
    generate_git_curated_snapshot,
    render_snapshot_comparison,
    render_snapshot_comparison_markdown,
)
from curve.classifier import (
    FEATURE_NAMES,
    RasterTrainingExample,
    TrainingExample,
    anchors_from_dataset,
    centroids_from_examples,
    classifier_prior_error,
    evaluate_classifier,
    evaluate_classifier_model,
    evaluate_classifier_ranking,
    examples_from_dataset,
    features_from_anchor,
    features_from_candidate,
    load_centroid_model,
    predict_label,
    raster_examples_from_dataset,
    render_classifier_evaluation_markdown,
    train_centroid_classifier,
)
from curve.mlx_classifier import (
    MLX_MODEL_TYPE,
    MlxClassifierTrainingConfig,
    is_mlx_available,
    mlx_classifier_runtime_status,
    train_mlx_transformer_classifier,
)
from curve.segmenters import (
    FlatColorSegmenter,
    MlxSamSegmenter,
    SegmentProposal,
    Segmenter,
    proposals_to_manifest,
)
from curve.self_learning import (
    apply_review_file,
    compare_retraining,
    create_review_file,
    gate_training_comparison,
    harvest_curated_pseudo_labels,
    harvest_pseudo_labels,
    merge_reviewed_pseudo_label_dataset,
    render_apply_review_markdown,
    render_harvest_markdown,
    render_review_markdown,
    render_self_learning_cycle_markdown,
    render_training_gate_markdown,
    render_training_comparison_markdown,
    run_self_learning_cycle,
    retrain_centroid_classifier,
)
from curve.refinement import (
    LOCAL_REFINEMENT_BACKEND,
    OPTIONAL_DIFFERENTIABLE_BACKENDS,
    RefinementConfig,
    available_refinement_backends,
    gate_refinement_result,
    refinement_backend_status,
    refine_manifest,
    render_refinement_gate_markdown,
)
from curve.curated import (
    check_curated_suite,
    load_curated_suite,
    render_curated_snapshot,
)
from curve.status import collect_runtime_status, render_runtime_status_markdown
from curve.sweeps import load_sweep_config, render_sweep_markdown, run_sweep
from curve.rendering import render_manifest_image, write_manifest_preview

__all__ = [
    "AnchorCandidate",
    "AnchorKind",
    "AnchorThresholdConfig",
    "BinaryMask",
    "CircleAnchor",
    "ColorMask",
    "DatasetSplit",
    "FEATURE_NAMES",
    "FlatColorSegmenter",
    "MaskComponent",
    "MlxSamSegmenter",
    "MLX_MODEL_TYPE",
    "MlxClassifierTrainingConfig",
    "mlx_classifier_runtime_status",
    "Point",
    "LOCAL_REFINEMENT_BACKEND",
    "OPTIONAL_DIFFERENTIABLE_BACKENDS",
    "QuadAnchor",
    "RasterTrainingExample",
    "RefinementConfig",
    "SCENE_MANIFEST_SCHEMA_VERSION",
    "ScoringConfig",
    "Scene",
    "SegmentProposal",
    "Segmenter",
    "StrokeAnchor",
    "SvgStyle",
    "SyntheticSample",
    "TrainingExample",
    "VectorizeRun",
    "anchor_to_manifest",
    "anchor_to_svg_element",
    "anchors_to_debug_svg",
    "anchors_from_dataset",
    "apply_review_file",
    "anchors_to_svg",
    "available_refinement_backends",
    "refinement_backend_status",
    "choose_best_anchor",
    "connected_components",
    "create_run_dir",
    "create_review_file",
    "classifier_prior_error",
    "check_curated_suite",
    "detect_cutout_strokes",
    "detect_primitive_anchors",
    "evaluate_runs",
    "evaluate_classifier",
    "evaluate_classifier_model",
    "evaluate_classifier_ranking",
    "examples_from_dataset",
    "features_from_anchor",
    "features_from_candidate",
    "flat_color_masks_from_image",
    "generate_synthetic_sample",
    "generate_synthetic_dataset",
    "generate_git_curated_snapshot",
    "gate_refinement_result",
    "gate_training_comparison",
    "harvest_curated_pseudo_labels",
    "harvest_pseudo_labels",
    "centroids_from_examples",
    "compare_git_snapshots",
    "compare_retraining",
    "compare_snapshots",
    "collect_runtime_status",
    "primitive_candidates_for_component",
    "load_centroid_model",
    "load_curated_suite",
    "load_sweep_config",
    "is_mlx_available",
    "merge_reviewed_pseudo_label_dataset",
    "proposals_to_manifest",
    "predict_label",
    "raster_examples_from_dataset",
    "profile_vectorize",
    "scene_from_flat_color_image",
    "scene_groups_to_manifest",
    "scene_layers_to_manifest",
    "scene_metrics_to_manifest",
    "scene_from_mask",
    "split_counts",
    "render_markdown_report",
    "render_html_report",
    "render_curated_snapshot",
    "render_classifier_evaluation_markdown",
    "render_eval_markdown",
    "render_apply_review_markdown",
    "render_harvest_markdown",
    "render_manifest_image",
    "render_review_markdown",
    "render_refinement_gate_markdown",
    "render_runtime_status_markdown",
    "render_self_learning_cycle_markdown",
    "render_snapshot_comparison",
    "render_snapshot_comparison_markdown",
    "render_sweep_markdown",
    "render_training_gate_markdown",
    "render_training_comparison_markdown",
    "refine_manifest",
    "retrain_centroid_classifier",
    "run_self_learning_cycle",
    "run_sweep",
    "write_manifest_preview",
    "write_html_report",
    "write_markdown_report",
    "write_vectorize_run",
    "write_eval_summary",
    "train_centroid_classifier",
    "train_mlx_transformer_classifier",
]
